[PHP]

memory_limit = 512M

max_execution_time = 300

max_input_time = 300

upload_max_filesize = 100M

post_max_size = 100M

max_input_vars = 5000

date.timezone = Europe/Rome

display_errors = On
display_startup_errors = On

error_reporting = E_ALL

log_errors = On

opcache.enable = 1
opcache.enable_cli = 1
opcache.validate_timestamps = 1
opcache.revalidate_freq = 0

realpath_cache_size = 4096K
realpath_cache_ttl = 600
